server:
  port: 8000

spring:
  datasource:
    url: "jdbc:h2:mem:demo-db;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;"
    driverClassName: "org.h2.Driver"

  h2:
    console:
      enabled=true:
    console.enabled: TRUE
  jpa:
    show-sql: TRUE
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: TRUE

  profiles:
    include:
      - "user-database"
      - "jwt"
