server:
  port: 8000

spring:
  datasource:
    url: "jdbc:h2:mem:demo-db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE"
    driverClassName: "org.h2.Driver"

  h2:
    console.enabled: TRUE

  jpa:
    show-sql: TRUE
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: TRUE

  profiles:
    include:
      - "user-database"
      - "jwt"
