server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reservationSystem?createDatabaseIfNotExist=true
    username: root # replace withyour username
    password: root # replace with your password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      schema: classpath:/schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

